export const styles = theme => ({
  backgroundWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'none',
  },
  background: {
    padding: 24,
    backgroundColor: '#fff',
    boxShadow: '0px 5px 5px rgba(80, 80, 80, .2)',
    borderRadius: 8,
    position: 'relative',
    width: '100%',
    maxWidth: 344,
  },
  opened: {
    display: 'flex',
  },
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: 48,
  },
  close: {
    position: 'absolute',
    right: 16,
    top: 16,
    cursor: 'pointer',
  },
  title: {
    fontSize: 13,
    fontWeight: 400,
    lineHeight: '20px',
    color: '#000',
  },
  items: {
    padding: '16px 20px',
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 16,
  },
  item: {
    padding: '8px 16px',
    fontSize: 14,
    fontWeight: 500,
    color: '#000',
    border: `1px solid ${theme.palette.secondary.main}`,
    borderRadius: 18,
    cursor: 'pointer',
    textTransform: 'uppercase',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    wordBreak: 'keep-all',
  },
});
